### ISSUE TITLE
在主界面上弹出一个dialog然后再没有关闭dialog的情况下有打开一个window，在关闭最后打开的这个window时，系统崩溃

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#15]
在主界面上弹出一个dialog然后在没有关闭dialog的情况下有打开一个新的window，在关闭最后打开的这个新的window时，系统崩溃，提示src/base/window_manager.c 104行异常。

谢谢！

**Comment by xianjimli** [comment]
我请同事看看。

**Comment by zhaoyangxia1990** [comment]
李工，这个确认是存在这个问题吗？
