### ISSUE TITLE
关于刷新区域赃矩形的问题

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#16]
1027*768的横屏，同软件翻转竖起来用，在左上角放一个动画，然后在右下角放一个动画，其它位置控件都是静态控件，通过在src/lcd/lcd_mem.inc中lcd_mem_flush函数中打印刷新区域，发现每个100ms左右刷新一次整个显示区域，而不是像只是刷新需要更新的两个小的显示区域，

谢谢！

**Comment by xianjimli** [comment]
AWTK使用的单脏矩形。别用软件旋转，要慢很多。

**Comment by zhaoyangxia1990** [comment]
唉！李工呀，项目到了关键时期，随便刷两个动画CPU使用率就100%，用的这种长条屏基本都是竖屏，成本压的很死，又只能用低端A7的平台，还是前期评估不够，现在只能换mipi接口内部控制器带旋转功能的屏在再试一把了。

**Comment by xianjimli** [comment]
我们一直在强调：不要用24位LCD，也不要旋转。24位不是对齐的，一个像素要读两次。旋转会破坏缓存的局部性， 频繁让缓存失效。两者会大幅降低性能。唉，为什么你们就是不听呢
