### ISSUE TITLE
关于界面色彩问题

### ISSUE THREAD

**Issue by zxc3489** [zlgopen/awtk-mvvm#22]
我可以通过color_picker在界面上展示一张彩色的图片，是否有类似的接口，可以生成一张灰阶图片？

**Comment by xianjimli** [comment]
没太明白。

> color_picker在界面上展示一张彩色的图片

这个是为了在图片上取某一点的颜色值吗？

> 可以生成一张灰阶图片

这与color_picker有什么关系吗？
