### ISSUE TITLE
适配ZMP1107平台编译报错

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#25]
![图片](https://user-images.githubusercontent.com/64031915/116024619-2e237600-a681-11eb-90aa-41141d0e243e.png)
awtk-linux-fb里面awtk_config.py里面的交叉编译工具路径、ZMP1107相关库路劲、头文件路径已经正确配置，编译没有问题，但是编译mvvm报错，FAE教我mvvm跟awtk-linux-fb一样增加相关路径，不懂如何操作，请指教！

**Comment by xianjimli** [comment]
我不了解ZMP。你在awtk-linux-fb/awtk_config.py里把相应的库加进去试试：查找字符串tkc_static，按类似的方式加。

如果你不行，你直接找FAE吧。
