### ISSUE TITLE
界面没有适时地跟模型同步

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk-mvvm#29]
如下图的按钮`login with gesture`有命令绑定：`v-on:click="{return, CloseWindow=True}"`，该命令是否有效是通过如下函数确定：
```C
bool_t login_can_return(login_t* login) {
  user_repository_t* r = app_globals_get_user_repository();
  user_t* user = user_repository_find_by_name(r, login->name.str);
  if (user == NULL) {
    return FALSE;
  }

  return user_have_gesture_password(user);
}
```
![Screenshot_20210709_085853](https://user-images.githubusercontent.com/2321526/125008262-bae0ac00-e094-11eb-9199-e0a6ae8b2a4b.png)

出现的问题是，`login_can_return`函数的结果会在其它模型（即其它窗口）内改变，然改变发生后再次切换回上面那个界面后，`MVVM`框架并没有执行`login_can_return`函数来更新按钮的状态，导致出现不同步现象。

_注：通过`Login`按钮切换窗口时没有将本窗口关闭，并且其它窗口用`navigator_back()`返回_

**Comment by xuchaoze** [comment]
需在上述界面的view_model的create函数上注册user_repository模型的EVT_PROP_CHANGED或者EVT_PROPS_CHANGED事件并转发到view_model上，如果你是参考awtk-mvvm-c-hello实现的，那可以这样：
user_repository_on(app_globals_get_user_repository(), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);

**Comment by xuchaoze** [comment]
需在上述界面的view_model的create函数上注册user_repository模型的EVT_PROP_CHANGED或者EVT_PROPS_CHANGED事件并转发到view_model上，如果你是参考awtk-mvvm-c-hello实现的，那可以这样：
user_repository_on(app_globals_get_user_repository(), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);

**Comment by ufbycd** [comment]
> 需在上述界面的view_model的create函数上注册user_repository模型的EVT_PROP_CHANGED或者EVT_PROPS_CHANGED事件并转发到view_model上，如果你是参考awtk-mvvm-c-hello实现的，那可以这样：
> user_repository_on(app_globals_get_user_repository(), EVT_PROP_CHANGED, (event_func_t)emitter_dispatch, vm);

嗯，按上述改了，确实可以。感谢。
