### ISSUE TITLE
navigator_confirm方法如何确认用户按的是哪个按钮？

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk-mvvm#31]
`confirm`是有交互过程的，但看了[文档](https://github.com/zlgopen/awtk-mvvm/blob/master/docs/12.navigate.md#1218-%E6%89%93%E5%BC%80%E5%86%85%E7%BD%AE%E7%9A%84%E7%A1%AE%E8%AE%A4%E7%AA%97%E5%8F%A3)也不知道`navigator_confirm`如何进行交互，如何确定按下的是哪个按钮？

**Comment by xianjimli** [comment]
看看它的返回值。

**Comment by ufbycd** [comment]
哦，文档的说明看得让人有点疑惑：`@return {ret_t} 返回RET_OK表示成功，否则表示失败。`
那返回值为0表示按了“确认”按钮？
