### ISSUE TITLE
如何查询内存占用？

### ISSUE THREAD

**Issue by ColdGenerator** [zlgopen/awtk-mvvm#36]
你好，我想知道demo运行时的实际内存占用, 有什么方法吗。
我在系统Ubuntu 18.04上使用smem查询，得到的USS（进程独自占用的内存，不包括共享库）有30+MB，这似乎不太合理。
![企业微信截图_16528614599898](https://user-images.githubusercontent.com/93175693/168990730-59eb94b7-478f-4f36-ac66-8496eea13be8.png)

**Comment by ColdGenerator** [comment]
谢谢，这个方法我会使用了；
现在有一个新的问题，我在awtk-mvvm中修改JERRY_GLOBAL_HEAP_SIZE的值，监测demo占用内存会有变化；
但是在awtk-jerryscript中修改JERRY_GLOBAL_HEAP_SIZE或者激活JERRY_SYSTEM_ALLOCATOR，demo占用内存没有明显变化；
是因为这个显示内存信息的函数只监测堆的使用，然后awtk-jerryscript默认变量存储到栈上吗？
但是我如果在awtk-jerryscript修改JERRY_GLOBAL_HEAP_SIZE到一个较小的值，执行demo会报错“Error: ERR_OUT_OF_MEMORY”，关于是否使用了jerrscript内存池，这一点我很迷惑。

**Comment by ColdGenerator** [comment]
补充一下，在mvvm中有设置”-DJERRY_EXTERNAL_CONTEXT=1 -DJERRY_GLOBAL_HEAP_SIZE=2048“；
在awtk-jerryscript中没有设置“-DJERRY_EXTERNAL_CONTEXT”，如果激活，执行demo会core dumped。

**Comment by xianjimli** [comment]
jerry内部的问题，我也不太了解。
