### ISSUE TITLE
在tk_thread线程中通过条件判断自动弹出popup信息提示框，点击提示框的【确认】键无法关闭提示框

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#39]
提示框通过navigator_to_ex打开，提示框的关闭通过{nothing, CloseWindow=true}命令关闭。而且第一次启动应用是可以关闭提示框，之后再弹出提示框无法关闭

**Comment by xianjimli** [comment]
非GUI线程不能操作GUI。

**Comment by zhaoyangxia1990** [comment]
操作mvvm的导航器navigator也不行吗？
