### ISSUE TITLE
可以实现时间选择设置？

### ISSUE THREAD

**Issue by zhu-Lucy** [zlgopen/awtk-mvvm#40]

**Comment by xianjimli** [comment]
看看这个是不是你需要的：https://github.com/zlgopen/awtk-widget-date-picker

**Comment by zhu-Lucy** [comment]
> 看看这个是不是你需要的：https://github.com/zlgopen/awtk-widget-date-pic
谢谢，这个我看过了，只能设置日期年月日。我想设置的是时分秒，这个可以实现吗。

**Comment by xianjimli** [comment]
你可以用text_selector实现。

**Comment by zhu-Lucy** [comment]
> 你可以用text_selector实现。

好的，谢谢
