### ISSUE TITLE
v-for-items动态渲染刷新速度问题

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#41]
应用场景如下：
![图片](https://user-images.githubusercontent.com/64031915/181740208-078594b9-63e3-4b2a-b3a6-90ff6cc759a4.png)

首次进入这个界面，默认选择第一组分类，很快就能显示第一组分类，但选择第二组分类的时候，大概需要等待5s才能刷新显示第二组分类，点击第三、四组也是一样速度很慢，但是从新点会第一组的速度很快就能刷新显示。
其中第一组的items最多，其它组数量比较少。我在切换分组的时候先调用darray_clear清空数组，然后再把新选择的分类组的所有选择项darray_push进入组数。window下模拟没有这种感觉，怎么点速度都还可以。

**Comment by xianjimli** [comment]
如果数量比较大，最好用TableView。

**Comment by zhaoyangxia1990** [comment]
我们需要水平滑动选择列表项，tableview不合适把。
我加载的列表项并不多，四个组分总共才51条，最多的一组19个，感觉不是加载数据的速度慢，可能不同的分组里面列表项的数量动态变化导致动态创建列表项哪里出了问题，从数量多的列表项切换到数量少的列表项打印信息如下：
![图片](https://user-images.githubusercontent.com/64031915/182267179-026b6683-c2fe-4dbf-bf03-1d0dc2b7df88.png)

**Comment by zhaoyangxia1990** [comment]
@xianjimli @xuchaoze 帮忙关注一下此问题，自己尝试改源码没能解决，谢谢！

**Comment by xuchaoze** [comment]
你好，可以提供一个可以重现的示例吗

**Comment by zhaoyangxia1990** [comment]
已发邮件到xuchaoze@zlg.cn，帮忙查看一下，谢谢！

**Comment by xuchaoze** [comment]
你好，更新一下mvvm。另外邮件中提到的另一个断言错误，能不能提供一个简单示例？

**Comment by xuchaoze** [comment]
你好，更新一下mvvm。另外邮件中提到的另一个断言错误，能不能提供一个简单示例？

**Comment by zhaoyangxia1990** [comment]
好的，我弄个发给你，感谢！
