### ISSUE TITLE
在pages(页面容器)下，有一页放入slider_view(滑动视图)控件，那么其他页的控件绑定v-data:focused属性不起作用！

### ISSUE THREAD

**Issue by zhu-Lucy** [zlgopen/awtk-mvvm#46]

**Comment by WNsACE** [comment]
你可以提供一个测试例子吗？我们这边测试一下啊

**Comment by zhu-Lucy** [comment]
> 你可以提供一个测试例子吗？我们这边测试一下啊

可以，要怎么发给你？留个qq邮箱还是？

**Comment by WNsACE** [comment]
你直接上传到这个 issues 的，可以添加附件文件的

**Comment by zhu-Lucy** [comment]
> 好的，
[demo.zip](https://github.com/zlgopen/awtk-mvvm/files/9603699/demo.zip)

**Comment by WNsACE** [comment]
里面好几个页面，是不是 callback 页面？要么直接提供一个简单可复现的项目？

**Comment by zhu-Lucy** [comment]
> 里面好几个页面，是不是 callback 页面？要么直接提供一个简单可复现的项目？
是callback页面，重新给你发。把callback页面里面的slide_view删掉和不删掉，重新运行比较结果不一样。
[demo1.zip](https://github.com/zlgopen/awtk-mvvm/files/9605964/demo1.zip)

**Comment by WNsACE** [comment]
好的，我们这边研究一下

**Comment by WNsACE** [comment]
我刚刚看了一下代码，是因为 slide_view 创建的时候会设置自身的，我提供一个 diff，你试一下合并到 awtk 看看是否能够修复你的代码
[awtk修复非focused时候设置slide_view激活子控件的逻辑.zip](https://github.com/zlgopen/awtk-mvvm/files/9626399/awtk.focused.slide_view.zip)

**Comment by zhu-Lucy** [comment]
已修复
