### ISSUE TITLE
edit输入数值无效的问题

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#47]
edit控件绑定模型的float变量，然后模型里面有个定时器会定时刷新界面，点击编辑框输入数据，然后点击确认输入之后，edit数值变回之前的数值。测试相关文件见附件！
[edit_test.zip](https://github.com/zlgopen/awtk-mvvm/files/9613428/edit_test.zip)

**Comment by WNsACE** [comment]
你修改 v-data:value 这里改成 v-data:text="{input_parameter, Trigger=Changing}"，看一下能够解决

**Comment by zhaoyangxia1990** [comment]
改成v-data:text="{input_parameter, Trigger=Changing}不能解决问题

**Comment by RainMic1019** [comment]
这个问题是 awtk 中 edit 控件代码没处理好导致的，现已修复，你可以更新 awtk 试一下。
awtk sha：7659b864bc533718a7df95318c24112f28203ef4
