### ISSUE TITLE
AWTK v-for-items动态渲染问题

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#48]
[issues.zip](https://github.com/zlgopen/awtk-mvvm/files/9838394/issues.zip)

做了个测试程序见附件，问题描述如下：
第一个分组【ABCDEFG】共6个选择项，第二个分组【HIJKLM】共12个选择项，第三个分组【NOPQRST】共18个选择项，第四个分组【UVWXYZ】共6个选择项
   启动程序首先进入第一个分组能正常显示6个选择的名称，再点击第二个分组、第三个分组，再点击第四个发现第四个分组的6个选项显示的名称全部是默认的名称，再点击回到第一个分组，发现第一个分组的6个选项显示的名称也全部是默认的名称。

怀疑渲染的控件数量刚刚是一页时存在问题。

**Comment by RainMic1019** [comment]
能发一个完整的重现示例项目吗?

**Comment by zhaoyangxia1990** [comment]
只要把xml放到design\default\ui下，把模型用gen.sh脚本生成view_model，然后在 application_init中注册模型，打开窗口就可以运行

static ret_t application_init(void) 
{
	log_debug("application_init\n");

	/* 注册mvvm模型 */
    //view_model_factory_register("edit_test", edit_test_view_model_create);
    view_model_factory_register("items_select_popup", items_select_popup_view_model_create);
	
	/* 显示主界面 */
	//navigator_to("edit_test");
    navigator_to("12_items_select");

	return RET_OK;
}

**Comment by RainMic1019** [comment]
v-for-items 的用法已弃用了，你可以看看 README.md 文档中提到的新的 v-for 用法，具体示例可以参考 demo13 和 demo35。
