### ISSUE TITLE
最新的源码编译不过，报错如下

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#50]
![图片](https://user-images.githubusercontent.com/64031915/208376053-bd5d2bc6-6d0f-47aa-81da-b6c150e3c3ca.png)

**Comment by xianjimli** [comment]
可以能是jerrryscript 版本不匹配。如果不需要JS，在SConstruct中：
将
```
os.environ['WITH_JS'] = 'true'
```
改为
```
os.environ['WITH_JS'] = 'false'
```
或者看看，README，确保取jerryscript兼容的版本。

**Comment by zhaoyangxia1990** [comment]
OK
