### ISSUE TITLE
v-for-items动态渲染窗体在关闭窗口时存在内存泄漏

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm#51]
[test_demo.zip](https://github.com/zlgopen/awtk-mvvm/files/10275049/test_demo.zip)

v-for-items动态渲染窗体在关闭窗口时存在内存泄漏，
测试demo见附件，在主界面重复点击进入v-for-items动态渲染窗体，会发现内存使用率在逐渐上升。

**Comment by aawuuu** [comment]
新版本的awtk已经解决了这个问题，你可以更新一下awtk与awtk-mvvm试试

**Comment by zhaoyangxia1990** [comment]
OK，感谢！
