### ISSUE TITLE
在这个框架下可以怎么建立model持久层

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-mvvm#56]
写一个界面，界面点击按钮进入菜单，在菜单设置后，希望这些设置能够保存起来，而不是再次进入的时候发现菜单又是最初的状态，实现思路这块有点纠结。
一个想法是在model层代码另外创建一个全局的model，加载view model的时候就把全局model的数据更新到view model中，对界面改动反映在view model对象上，退出页面销毁view model的时候就把改动的view model数据保存回全局model，这是我能想到的最简单的方法，但感觉这样一来view model就不知道有什么作用了，打开关闭视图都有viewmodel内存开销，为什么不放弃view model直接去修改全局model。
另外看了demo12的做法，感觉只是用request的在view model直接传递数据，最后temp和humidity保存在home的view model中，home作为第一个打开的界面生命周期一直维持到应用关闭。
不知道这块专业的设计思路是咋样的呢。

我写menu的做法：
![image](https://github.com/zlgopen/awtk-mvvm/assets/54085641/a99391b9-c361-485c-bbb3-415fa7554577)

**Comment by xianjimli** [comment]
可以直接用app_conf模型，使用或json/ini等模型。
