### ISSUE TITLE
对json的增删改查存在bug

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-mvvm#57]
试了下demo25，感觉所有配置都存在一个json上，而且不能指定路径，不太灵活。
照着demo_conf的方法直接把本地Json作为viewmodel，发现有点问题：
1. add数据之后数据没法根据绑定规则渲染出来，就是item.xxx之类，要点击reload才正常，demo25的例子就正常，add的数据能直接正常渲染。
2. 没有reload而新加的数据，如果remove，所有没有reload的数据都会被删除，而demo25就是点哪个数据只删哪个数据

repro:
[local_json_conf_crud_test.zip](https://github.com/user-attachments/files/16521904/local_json_conf_crud_test.zip)

这个bug能否解决？谢谢。

**Comment by xianjimli** [comment]
是有问题。我先看看，谢谢。

**Comment by xianjimli** [comment]
你更新一下awtk-mvvm，参考demo_conf和demo25的例子试试:
* add 界面使用 conf_add 模型，不指定URL，使用父conf模型，可以指定初始参数。
* edit 界面使用 conf_edit 模型，不指定URL，使用父conf模型。
* detail 界面使用 conf_detail 模型，不指定URL，使用父conf模型。

今天有事，文档明天再更新。

**Comment by Tracker647** [comment]
好的，功能正常了，谢谢。

**Comment by Tracker647** [comment]
附上测试demo: [local_json_conf_crud_test.zip](https://github.com/user-attachments/files/16568885/local_json_conf_crud_test.zip)

**Comment by xianjimli** [comment]
文档：https://gitee.com/zlgopen/awtk-mvvm/blob/master/docs/view_model_conf.md

**Comment by Tracker647** [comment]
好的，谢谢。
