### ISSUE TITLE
MVVM-JS能读写文件吗？

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-mvvm#58]
比如onCreate从json加载数据，onExit的时候保存数据到json？
看了下jerryscripy对于json操作的api只有parse和stringify, 属于格式转换，增删查改的函数貌似没有。
官方文档看了下也说没有对应支持，这部分靠iotjs实现，但是iotjs不更很多年了。

**Comment by xianjimli** [comment]
增加了几个函数，你更新试试，谢谢：https://github.com/zlgopen/awtk-mvvm/blob/master/docs/js_ext_api.md

**Comment by Tracker647** [comment]
好的，正常工作，基于jsdemo13做了个json持久化的改进：

[js_mvvm_list_item_test.zip](https://github.com/user-attachments/files/16541715/js_mvvm_list_item_test.zip)

js model那章的生命周期建议更新一下，OnExit已经没用了（对应的应该是OnDestroy）。
另外问下awtk-web可以支持js model吗？试了下不行，看Log没有加载jerryscript部分。

**Comment by Tracker647** [comment]
好的，正常工作，基于jsdemo13做了个json持久化的改进：


[js_mvvm_list_item_test.zip](https://github.com/user-attachments/files/16541878/js_mvvm_list_item_test.zip)

js model那章的生命周期建议更新一下，OnExit已经没用了（对应的应该是OnDestroy），谢谢。

**Comment by xianjimli** [comment]
OnExit是应用程序退出，不是模型销毁。
