### ISSUE TITLE
列表按钮没法动态设置enable属性

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-mvvm#59]
有个需求，列表渲染的前几个item是固定不能动的，这些item的remove按钮enable属性要为false。
于是自己给item添加了个editable的属性，想着在button标签上v-data:enable="{item.editable}"属性就能解决问题，但是运行发现button还是normal状态，直接写死成enable="false"，还是同样能按，哪怕designer上已经显示成disable样式了。

repro:
[js_mvvm_list_item_test.zip](https://github.com/user-attachments/files/16592407/js_mvvm_list_item_test.zip)

麻烦跟进一下，谢谢。

**Comment by xianjimli** [comment]
enable是默认由命令的can_exec决定的，如果想自己决定，在绑定规则中加auto_disable=false

**Comment by Tracker647** [comment]
> auto_disable=false

在xml中吗？试了下没用啊，我是这样写的：
        <button w="70" v-on:click="{remove, Args=fscript?index=index}" v-data:auto_disable="{item.editable}" v-data:enable="{item.editable}" text="Remove"/>
          <button w="50" v-on:click="{sale, Args=fscript?index=index}" v-data:auto_disable="{item.editable}" v-data:enable="{item.editable}" text="Sale"/>

试了写：
auto_disable=”false“
v-data:auto_disable="{item.editable}"
都没用。

有个issue说要定义can_exec，我在viewmodel定义了：
ViewModel('books', {
  data: {
    items: [],
    data_file_root: './design/default/data/books.json'
  },
...
  canExec: function(args){
      return args.editable;
    },
...
}
也没用。

**Comment by xianjimli** [comment]
在这个文档中找 AutoDisable：

https://github.com/zlgopen/awtk-mvvm/blob/master/docs/11.command_binding.md

**Comment by Tracker647** [comment]
OK, 解决，原来要写到命令绑定上。
```
<button w="70" text="Remove" v-data:enable="{item.editable}" v-on:click="{remove, AutoDisable=false, Args=fscript?index=index}"/>
          <button w="50" text="Sale" v-data:enable="{item.editable}" v-on:click="{sale, AutoDisable=false, Args=fscript?index=index}"/>
```
